import type { AnyRecipe } from '../../../domain/types';
import { buildRecipe } from './build';

/**
 * The demo family's library, newest first. Only the local (demo) backend loads
 * these; a real family starts with an empty library.
 */

export const SEED_LIBRARY: readonly AnyRecipe[] = [
  buildRecipe({
    slug: 'one-pan-lemon-chicken-rice',
    title: 'One-Pan Lemon Chicken & Rice',
    description:
      'Crisp-skinned thighs baked over lemony, garlicky rice — one pan, a little patience, and a cool dill yogurt to finish.',
    source: { site: 'saltandsimmer.com' },
    servings: 4,
    prepMin: 15,
    cookMin: 65,
    kcal: 540,
    kcalEstimated: true,
    sourceRating: 4.6,
    userRating: 4,
    tags: ['Gluten-free', 'One-pan'],
    ingredients: [
      '8 bone-in, skin-on chicken thighs (about 1.1 kg)',
      '300 g long-grain white rice (rinsed)',
      '2 lemons (1 zested and juiced, 1 sliced)',
      '1 yellow onion (finely chopped)',
      '4 garlic cloves (grated)',
      '750 ml chicken stock (hot)',
      '1 tsp dried oregano',
      '1 tsp smoked paprika',
      '2 tbsp olive oil',
      '1½ tsp fine salt (plus a pinch for the sauce)',
      '½ tsp black pepper',
      '1 bunch fresh dill (about 20 g)',
      '200 g Greek yogurt',
    ],
    equipment: [
      '30 cm oven-safe skillet or shallow Dutch oven',
      'Foil or a tight-fitting lid',
      'Fine grater or zester',
      'Small mixing bowl',
    ],
    steps: [
      [
        'Heat the oven to 200 °C. Pat the chicken dry and season all over with the salt, pepper, paprika, oregano and the zest of 1 lemon.',
        [0, 9, 10, 7, 6, 2], 'Season the chicken',
      ],
      [
        'Warm the oil in the skillet over medium-high heat. Lay the chicken in skin-side down and sear 8 min until deep golden. Move to a plate.',
        [8, 0], 'Sear',
      ],
      [
        'Pour off all but 2 tbsp of fat. Add the onion and cook 4 min until soft, then stir in the garlic for 1 min.',
        [3, 4], 'Soften the onion',
      ],
      ['Add the rice and toast 2 min, stirring, until the edges turn translucent.', [1], 'Toast the rice'],
      [
        'Pour in the hot stock and the juice of the zested lemon; bring to a simmer. Nestle the chicken on top, skin-side up, and tuck the lemon slices around it.',
        [5, 2, 0], 'Add the stock',
      ],
      [
        'Cover the pan tightly with foil and bake 50 min in the oven, until the rice is tender and the liquid is absorbed. Meanwhile, stir the dill into the yogurt with a pinch of salt and chill 15 min.',
        [11, 12, 9], 'Bake',
      ],
      ['Uncover and rest 10 min. Scatter with the remaining dill and serve with the yogurt sauce.', [11], 'Rest and serve'],
    ],
  }),

  buildRecipe({
    slug: 'shakshuka-with-feta',
    title: 'Shakshuka with Feta',
    description: 'Eggs poached in a smoky, cumin-spiced tomato sauce, finished with salty feta.',
    source: 'mine',
    servings: 2,
    prepMin: 10,
    cookMin: 25,
    kcal: 340,
    userRating: 5,
    tags: ['Vegetarian', 'Gluten-free'],
    ingredients: [
      '4 eggs',
      '400 g crushed tomatoes',
      '150 g cherry tomatoes (halved)',
      '1 yellow onion (finely chopped)',
      '2 garlic cloves (sliced)',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '2 tbsp olive oil',
      '½ tsp salt',
      '150 g feta (crumbled)',
    ],
    equipment: ['Large skillet with a lid'],
    steps: [
      ['Warm the oil in a large skillet over medium heat. Add the onion and cook 6 min until soft and golden.', [7, 3]],
      ['Stir in the garlic, cumin and paprika and cook 1 min until fragrant.', [4, 5, 6]],
      ['Tip in the crushed and cherry tomatoes with the salt. Simmer for 10 min, until thick enough to hold a well.', [1, 2, 8]],
      ['Make 4 wells and crack an egg into each. Cover and cook 6–8 min, until the whites are set but the yolks are still soft.', [0]],
      ['Scatter over the feta and serve straight from the pan.', [9]],
    ],
  }),

  buildRecipe({
    slug: 'miso-glazed-salmon-bok-choy',
    title: 'Miso-Glazed Salmon & Bok Choy',
    description: 'Salty-sweet miso salmon, charred bok choy and lime-bright rice in under half an hour.',
    source: { site: 'weeknightpan.co' },
    servings: 2,
    prepMin: 10,
    cookMin: 15,
    kcal: 460,
    sourceRating: 4.4,
    tags: ['Pescatarian', 'Dairy-free'],
    ingredients: [
      '2 salmon fillets',
      '3 tbsp white miso',
      '1 tbsp soy sauce',
      '150 g long-grain rice (rinsed)',
      '2 garlic cloves (grated)',
      '1 lime (juiced)',
      '1 tbsp olive oil',
      '4 heads baby bok choy (halved)',
      '1 bunch scallions (sliced)',
    ],
    equipment: ['Sheet pan', 'Skillet', 'Saucepan'],
    steps: [
      ['Heat the oven to 220 °C. Cook the rice in a pan of simmering water for 12 min, then drain and keep warm.', [3]],
      ['Whisk the miso, soy sauce, garlic and lime juice. Brush half over the salmon and marinate 10 min.', [1, 2, 4, 5, 0]],
      ['Lay the salmon on a lined tray and roast 10 min, brushing with the rest of the glaze halfway.', [0]],
      ['Meanwhile, warm the oil in a skillet, add the bok choy cut-side down and fry 3 min until charred.', [6, 7]],
      ['Serve the salmon over the rice with the bok choy, scattered with scallions.', [8]],
    ],
  }),

  buildRecipe({
    slug: 'sweet-potato-black-bean-tacos',
    title: 'Sweet Potato & Black Bean Tacos',
    description: 'Smoky roast sweet potato, cumin beans and crunchy lime cabbage in warm corn tortillas.',
    source: { site: 'greenstreetkitchen.com' },
    servings: 4,
    prepMin: 10,
    cookMin: 30,
    kcal: 410,
    sourceRating: 4.3,
    tags: ['Vegan'],
    ingredients: [
      '2 sweet potatoes (cut into 2 cm cubes)',
      '1 can black beans (drained)',
      '2 limes',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '2 tbsp olive oil',
      '½ tsp salt',
      '8 corn tortillas',
      '1 avocado',
      '¼ red cabbage (finely shredded)',
      '1 bunch cilantro',
    ],
    equipment: ['Sheet pan', 'Small saucepan'],
    steps: [
      ['Heat the oven to 220 °C. Toss the sweet potatoes with the oil, cumin, paprika and salt.', [0, 5, 3, 4, 6]],
      ['Spread on a tray and roast 25 min, turning once, until caramelised at the edges.', [0]],
      ['Warm the black beans in a small pan with a splash of water for 5 min, then lightly mash.', [1]],
      ['Toss the cabbage with the juice of 1 lime. Mash the avocado with the rest of the lime juice.', [9, 2, 8]],
      ['Warm the tortillas and fill with the beans, sweet potato, cabbage, avocado and cilantro.', [7, 10]],
    ],
  }),

  buildRecipe({
    slug: 'grandmas-lentil-soup',
    title: 'Grandma’s Lentil Soup',
    description: 'The one everyone asks for: thick, lemony, and better the next day.',
    source: 'mine',
    servings: 6,
    prepMin: 15,
    cookMin: 55,
    kcal: 290,
    kcalEstimated: true,
    userRating: 5,
    tags: ['Vegan', 'Gluten-free'],
    ingredients: [
      '300 g brown lentils (rinsed)',
      '2 carrots (diced)',
      '2 celery stalks (diced)',
      '1 yellow onion (diced)',
      '3 garlic cloves (minced)',
      '400 g crushed tomatoes',
      '1.5 l vegetable stock',
      '1 tsp ground cumin',
      '2 bay leaves',
      '1 lemon (juiced)',
      '100 g baby spinach',
      '3 tbsp olive oil',
      '1 tsp salt',
      '½ tsp black pepper',
    ],
    equipment: ['Large pot'],
    steps: [
      ['Warm the oil in a large pot over medium heat. Add the onion, carrots and celery and cook 10 min until soft.', [11, 3, 1, 2]],
      ['Stir in the garlic and cumin for 1 min, until fragrant.', [4, 7]],
      ['Add the lentils, tomatoes, stock, bay leaves, salt and pepper. Bring to a boil, then simmer 40 min until the lentils are tender.', [0, 5, 6, 8, 12, 13]],
      ['Fish out the bay leaves. Stir in the spinach until wilted, about 2 min.', [10]],
      ['Finish with the lemon juice, taste for salt, and serve.', [9]],
    ],
  }),

  buildRecipe({
    slug: 'peanut-noodle-stir-fry',
    title: 'Peanut Noodle Stir-Fry',
    description: 'Slippery rice noodles in a punchy peanut-lime sauce with crisp vegetables.',
    source: { site: 'weeknightpan.co' },
    servings: 3,
    prepMin: 15,
    cookMin: 15,
    kcal: 610,
    sourceRating: 4.7,
    tags: ['Vegetarian'],
    ingredients: [
      '250 g rice noodles',
      '3 tbsp soy sauce',
      '2 garlic cloves (grated)',
      '1 lime (juiced)',
      '2 carrots (cut into matchsticks)',
      '2 tbsp vegetable oil',
      '1 tbsp sugar',
      '½ tsp salt',
      '4 tbsp peanut butter',
      '1 tbsp sesame oil',
      '1 red bell pepper (sliced)',
      '1 bunch scallions (sliced)',
    ],
    equipment: ['Wok or large skillet', 'Mixing bowl'],
    steps: [
      ['Cover the noodles with just-boiled water and soak 8 min, then drain and rinse under cold water.', [0]],
      ['Whisk the peanut butter, soy sauce, lime juice, sugar, sesame oil and 4 tbsp warm water into a smooth sauce.', [8, 1, 3, 6, 9]],
      ['Heat the oil in a wok over high heat. Add the carrots and pepper and fry 3 min, until just tender.', [5, 4, 10]],
      ['Add the garlic and scallions, then the noodles and sauce. Toss for 2 min until glossy and hot through.', [2, 11, 0]],
      ['Season with the salt and serve straight away.', [7]],
    ],
  }),

  buildRecipe({
    slug: 'wild-mushroom-risotto',
    title: 'Wild Mushroom Risotto',
    description: 'Deeply browned mushrooms folded through a creamy, parmesan-rich risotto.',
    source: 'mine',
    servings: 4,
    prepMin: 10,
    cookMin: 35,
    kcal: 480,
    userRating: 4,
    tags: ['Vegetarian', 'Gluten-free'],
    ingredients: [
      '300 g arborio rice',
      '1.2 l vegetable stock (hot)',
      '60 g parmesan (grated)',
      '40 g butter',
      '2 garlic cloves (minced)',
      '2 tbsp olive oil',
      '½ tsp black pepper',
      '400 g cremini mushrooms (sliced)',
      '2 shallots (finely chopped)',
      '150 ml dry white wine',
    ],
    equipment: ['Wide heavy pan', 'Saucepan', 'Ladle'],
    steps: [
      ['Warm the oil in a wide pan over medium-high heat. Add the mushrooms and fry 6 min until browned; set aside.', [5, 7]],
      ['Lower the heat, add half the butter and the shallots, and cook 4 min until soft. Stir in the garlic.', [3, 8, 4]],
      ['Add the rice and toast 2 min, then pour in the wine and let it bubble away.', [0, 9]],
      ['Add the hot stock a ladle at a time, stirring, until the rice is creamy and just tender, about 18 min.', [1]],
      ['Stir in the mushrooms, parmesan, the rest of the butter and the pepper. Rest 2 min before serving.', [7, 2, 3, 6]],
    ],
  }),

  buildRecipe({
    slug: 'brown-butter-banana-bread',
    title: 'Brown-Butter Banana Bread',
    description: 'Nutty brown butter and very ripe bananas make a loaf that stays moist for days.',
    source: { site: 'saltandsimmer.com' },
    servings: 10,
    servingUnit: 'slice',
    prepMin: 15,
    cookMin: 60,
    kcal: 280,
    sourceRating: 4.8,
    tags: ['Vegetarian'],
    ingredients: [
      '3 bananas (very ripe, mashed)',
      '115 g butter',
      '2 eggs',
      '60 ml milk',
      '1 tsp cinnamon',
      '150 g sugar',
      '250 g all-purpose flour',
      '1 tsp baking soda',
      '½ tsp salt',
    ],
    equipment: ['Loaf tin', 'Small saucepan', 'Mixing bowl'],
    steps: [
      'Heat the oven to 175 °C and line a loaf tin.',
      ['Melt the butter in a small pan and cook 4 min, swirling, until nutty and brown. Cool 10 min.', [1]],
      ['Whisk the bananas, brown butter, sugar, eggs and milk. Fold in the flour, baking soda, cinnamon and salt.', [0, 1, 5, 2, 3, 6, 7, 4, 8]],
      'Scrape into the tin and bake 55 min, until a skewer comes out clean.',
      'Cool in the tin for 15 min before slicing.',
    ],
  }),

  buildRecipe({
    slug: 'lemon-oregano-chicken-skewers',
    title: 'Lemon-Oregano Chicken Skewers',
    description: 'Charred, garlicky chicken skewers with blistered tomatoes over simple rice.',
    source: 'mine',
    servings: 4,
    prepMin: 20,
    cookMin: 25,
    kcal: 430,
    userRating: 4,
    tags: ['Gluten-free', 'Dairy-free'],
    ingredients: [
      '700 g chicken thighs (boneless, cut into chunks)',
      '2 lemons (zested and juiced)',
      '3 garlic cloves (grated)',
      '2 tsp dried oregano',
      '1 tsp smoked paprika',
      '250 g long-grain rice',
      '250 g cherry tomatoes',
      '3 tbsp olive oil',
      '1 tsp salt',
      '½ tsp black pepper',
      '1 red onion (cut into wedges)',
      '1 bunch flat-leaf parsley',
    ],
    equipment: ['Skewers', 'Grill pan', 'Saucepan'],
    steps: [
      ['Mix the lemon zest and juice, garlic, oregano, paprika, oil, salt and pepper. Add the chicken and marinate 20 min.', [1, 2, 3, 4, 7, 8, 9, 0]],
      ['Meanwhile, cook the rice in simmering water for 12 min, then drain and cover.', [5]],
      ['Thread the chicken, onion and tomatoes onto skewers.', [0, 10, 6]],
      ['Heat a grill pan over high heat, add the skewers and cook 12 min, turning, until charred and cooked through.', [0]],
      ['Rest 5 min, then scatter with parsley and serve over the rice.', [11]],
    ],
  }),
];
